# coding: utf-8

"""
    WSO2 API Manager - Admin

    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApplicationThrottlePolicyList(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'list': 'list[GenericThrottlePolicy]'
    }

    attribute_map = {
        'count': 'count',
        'list': 'list'
    }

    def __init__(self, count=None, list=None):
        """
        ApplicationThrottlePolicyList - a model defined in Swagger
        """

        self._count = None
        self._list = None

        if count is not None:
          self.count = count
        if list is not None:
          self.list = list

    @property
    def count(self):
        """
        Gets the count of this ApplicationThrottlePolicyList.
        Number of Application throttle policies returned. 

        :return: The count of this ApplicationThrottlePolicyList.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this ApplicationThrottlePolicyList.
        Number of Application throttle policies returned. 

        :param count: The count of this ApplicationThrottlePolicyList.
        :type: int
        """

        self._count = count

    @property
    def list(self):
        """
        Gets the list of this ApplicationThrottlePolicyList.

        :return: The list of this ApplicationThrottlePolicyList.
        :rtype: list[GenericThrottlePolicy]
        """
        return self._list

    @list.setter
    def list(self, list):
        """
        Sets the list of this ApplicationThrottlePolicyList.

        :param list: The list of this ApplicationThrottlePolicyList.
        :type: list[GenericThrottlePolicy]
        """

        self._list = list

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApplicationThrottlePolicyList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
