# coding: utf-8

"""
    WSO2 API Manager - Admin

    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BlockingCondition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'condition_id': 'str',
        'condition_type': 'str',
        'condition_value': 'str'
    }

    attribute_map = {
        'condition_id': 'conditionId',
        'condition_type': 'conditionType',
        'condition_value': 'conditionValue'
    }

    def __init__(self, condition_id=None, condition_type=None, condition_value=None):
        """
        BlockingCondition - a model defined in Swagger
        """

        self._condition_id = None
        self._condition_type = None
        self._condition_value = None

        if condition_id is not None:
          self.condition_id = condition_id
        self.condition_type = condition_type
        self.condition_value = condition_value

    @property
    def condition_id(self):
        """
        Gets the condition_id of this BlockingCondition.

        :return: The condition_id of this BlockingCondition.
        :rtype: str
        """
        return self._condition_id

    @condition_id.setter
    def condition_id(self, condition_id):
        """
        Sets the condition_id of this BlockingCondition.

        :param condition_id: The condition_id of this BlockingCondition.
        :type: str
        """

        self._condition_id = condition_id

    @property
    def condition_type(self):
        """
        Gets the condition_type of this BlockingCondition.

        :return: The condition_type of this BlockingCondition.
        :rtype: str
        """
        return self._condition_type

    @condition_type.setter
    def condition_type(self, condition_type):
        """
        Sets the condition_type of this BlockingCondition.

        :param condition_type: The condition_type of this BlockingCondition.
        :type: str
        """
        if condition_type is None:
            raise ValueError("Invalid value for `condition_type`, must not be `None`")

        self._condition_type = condition_type

    @property
    def condition_value(self):
        """
        Gets the condition_value of this BlockingCondition.

        :return: The condition_value of this BlockingCondition.
        :rtype: str
        """
        return self._condition_value

    @condition_value.setter
    def condition_value(self, condition_value):
        """
        Sets the condition_value of this BlockingCondition.

        :param condition_value: The condition_value of this BlockingCondition.
        :type: str
        """
        if condition_value is None:
            raise ValueError("Invalid value for `condition_value`, must not be `None`")

        self._condition_value = condition_value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BlockingCondition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
