# coding: utf-8

"""
    WSO2 API Manager - Admin

    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GenericThrottlePolicy1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'policy_id': 'str',
        'policy_name': 'str',
        'display_name': 'str',
        'description': 'str',
        'is_deployed': 'bool',
        'default_limit': 'ApplicationLevelThrottlePolicyListDefaultLimit'
    }

    attribute_map = {
        'policy_id': 'policyId',
        'policy_name': 'policyName',
        'display_name': 'displayName',
        'description': 'description',
        'is_deployed': 'isDeployed',
        'default_limit': 'defaultLimit'
    }

    def __init__(self, policy_id=None, policy_name=None, display_name=None, description=None, is_deployed=False, default_limit=None):
        """
        GenericThrottlePolicy1 - a model defined in Swagger
        """

        self._policy_id = None
        self._policy_name = None
        self._display_name = None
        self._description = None
        self._is_deployed = None
        self._default_limit = None

        if policy_id is not None:
          self.policy_id = policy_id
        self.policy_name = policy_name
        if display_name is not None:
          self.display_name = display_name
        if description is not None:
          self.description = description
        if is_deployed is not None:
          self.is_deployed = is_deployed
        if default_limit is not None:
          self.default_limit = default_limit

    @property
    def policy_id(self):
        """
        Gets the policy_id of this GenericThrottlePolicy1.

        :return: The policy_id of this GenericThrottlePolicy1.
        :rtype: str
        """
        return self._policy_id

    @policy_id.setter
    def policy_id(self, policy_id):
        """
        Sets the policy_id of this GenericThrottlePolicy1.

        :param policy_id: The policy_id of this GenericThrottlePolicy1.
        :type: str
        """

        self._policy_id = policy_id

    @property
    def policy_name(self):
        """
        Gets the policy_name of this GenericThrottlePolicy1.

        :return: The policy_name of this GenericThrottlePolicy1.
        :rtype: str
        """
        return self._policy_name

    @policy_name.setter
    def policy_name(self, policy_name):
        """
        Sets the policy_name of this GenericThrottlePolicy1.

        :param policy_name: The policy_name of this GenericThrottlePolicy1.
        :type: str
        """
        if policy_name is None:
            raise ValueError("Invalid value for `policy_name`, must not be `None`")

        self._policy_name = policy_name

    @property
    def display_name(self):
        """
        Gets the display_name of this GenericThrottlePolicy1.

        :return: The display_name of this GenericThrottlePolicy1.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """
        Sets the display_name of this GenericThrottlePolicy1.

        :param display_name: The display_name of this GenericThrottlePolicy1.
        :type: str
        """

        self._display_name = display_name

    @property
    def description(self):
        """
        Gets the description of this GenericThrottlePolicy1.

        :return: The description of this GenericThrottlePolicy1.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this GenericThrottlePolicy1.

        :param description: The description of this GenericThrottlePolicy1.
        :type: str
        """

        self._description = description

    @property
    def is_deployed(self):
        """
        Gets the is_deployed of this GenericThrottlePolicy1.

        :return: The is_deployed of this GenericThrottlePolicy1.
        :rtype: bool
        """
        return self._is_deployed

    @is_deployed.setter
    def is_deployed(self, is_deployed):
        """
        Sets the is_deployed of this GenericThrottlePolicy1.

        :param is_deployed: The is_deployed of this GenericThrottlePolicy1.
        :type: bool
        """

        self._is_deployed = is_deployed

    @property
    def default_limit(self):
        """
        Gets the default_limit of this GenericThrottlePolicy1.

        :return: The default_limit of this GenericThrottlePolicy1.
        :rtype: ApplicationLevelThrottlePolicyListDefaultLimit
        """
        return self._default_limit

    @default_limit.setter
    def default_limit(self, default_limit):
        """
        Sets the default_limit of this GenericThrottlePolicy1.

        :param default_limit: The default_limit of this GenericThrottlePolicy1.
        :type: ApplicationLevelThrottlePolicyListDefaultLimit
        """

        self._default_limit = default_limit

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GenericThrottlePolicy1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
