# coding: utf-8

"""
    WSO2 API Manager - Admin

    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_adminclient
from wso2_apim_adminclient.rest import ApiException
from wso2_apim_adminclient.apis.custom_rules_api import CustomRulesApi


class TestCustomRulesApi(unittest.TestCase):
    """ CustomRulesApi unit test stubs """

    def setUp(self):
        self.api = wso2_apim_adminclient.apis.custom_rules_api.CustomRulesApi()

    def tearDown(self):
        pass

    def test_throttling_policies_custom_get(self):
        """
        Test case for throttling_policies_custom_get

        Get all Custom Rules
        """
        pass

    def test_throttling_policies_custom_post(self):
        """
        Test case for throttling_policies_custom_post

        Add a Custom Rule
        """
        pass

    def test_throttling_policies_custom_rule_id_delete(self):
        """
        Test case for throttling_policies_custom_rule_id_delete

        Delete a Custom Rule
        """
        pass

    def test_throttling_policies_custom_rule_id_get(self):
        """
        Test case for throttling_policies_custom_rule_id_get

        Retrieve a Custom Rule
        """
        pass

    def test_throttling_policies_custom_rule_id_put(self):
        """
        Test case for throttling_policies_custom_rule_id_put

        Update a Custom Rule
        """
        pass


if __name__ == '__main__':
    unittest.main()
