# coding: utf-8

"""
    WSO2 API Manager - Admin

    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_adminclient
from wso2_apim_adminclient.rest import ApiException
from wso2_apim_adminclient.apis.mediation_individual_api import MediationIndividualApi


class TestMediationIndividualApi(unittest.TestCase):
    """ MediationIndividualApi unit test stubs """

    def setUp(self):
        self.api = wso2_apim_adminclient.apis.mediation_individual_api.MediationIndividualApi()

    def tearDown(self):
        pass

    def test_policies_mediation_mediation_policy_id_delete(self):
        """
        Test case for policies_mediation_mediation_policy_id_delete

        Delete an API
        """
        pass

    def test_policies_mediation_mediation_policy_id_get(self):
        """
        Test case for policies_mediation_mediation_policy_id_get

        Get a global mediation squence
        """
        pass

    def test_policies_mediation_mediation_policy_id_put(self):
        """
        Test case for policies_mediation_mediation_policy_id_put

        Update an mediation policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
