# coding: utf-8

"""
    WSO2 API Manager - Admin

    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_adminclient
from wso2_apim_adminclient.rest import ApiException
from wso2_apim_adminclient.apis.application_policies_api import ApplicationPoliciesApi


class TestApplicationPoliciesApi(unittest.TestCase):
    """ ApplicationPoliciesApi unit test stubs """

    def setUp(self):
        self.api = wso2_apim_adminclient.apis.application_policies_api.ApplicationPoliciesApi()

    def tearDown(self):
        pass

    def test_throttling_policies_application_get(self):
        """
        Test case for throttling_policies_application_get

        Get all Application level throttle policies
        """
        pass

    def test_throttling_policies_application_policy_id_delete(self):
        """
        Test case for throttling_policies_application_policy_id_delete

        Delete an Application level throttle policy
        """
        pass

    def test_throttling_policies_application_policy_id_get(self):
        """
        Test case for throttling_policies_application_policy_id_get

        Retrieve an Application Policy
        """
        pass

    def test_throttling_policies_application_policy_id_put(self):
        """
        Test case for throttling_policies_application_policy_id_put

        Update an Application level throttle policy
        """
        pass

    def test_throttling_policies_application_post(self):
        """
        Test case for throttling_policies_application_post

        Add an Application level throttle policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
