# coding: utf-8

"""
    WSO2 API Manager - Admin

    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_adminclient
from wso2_apim_adminclient.rest import ApiException
from wso2_apim_adminclient.models.description_of_individual_errors_that_may_have_occurred_during_a_request_ import DescriptionOfIndividualErrorsThatMayHaveOccurredDuringARequest_


class TestDescriptionOfIndividualErrorsThatMayHaveOccurredDuringARequest_(unittest.TestCase):
    """ DescriptionOfIndividualErrorsThatMayHaveOccurredDuringARequest_ unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDescriptionOfIndividualErrorsThatMayHaveOccurredDuringARequest_(self):
        """
        Test DescriptionOfIndividualErrorsThatMayHaveOccurredDuringARequest_
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = wso2_apim_adminclient.models.description_of_individual_errors_that_may_have_occurred_during_a_request_.DescriptionOfIndividualErrorsThatMayHaveOccurredDuringARequest_()
        pass


if __name__ == '__main__':
    unittest.main()
