# coding: utf-8

"""
    WSO2 API Manager - Admin

    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_adminclient
from wso2_apim_adminclient.rest import ApiException
from wso2_apim_adminclient.apis.api_collection_api import APICollectionApi


class TestAPICollectionApi(unittest.TestCase):
    """ APICollectionApi unit test stubs """

    def setUp(self):
        self.api = wso2_apim_adminclient.apis.api_collection_api.APICollectionApi()

    def tearDown(self):
        pass

    def test_policies_mediation_get(self):
        """
        Test case for policies_mediation_get

        Retrieve/Search APIs 
        """
        pass


if __name__ == '__main__':
    unittest.main()
